config/routes.rb
Rails.application.routes.draw do
  get 'notifications/mark_all_read'
  devise_for :users

  # Define health check route
  get "up" => "rails/health#show", as: :rails_health_check

  get "/dashboard" => "pages#dashboard"

  root "events#index"

  # Defines the root path route ("/")
  resources :events, only: [:index, :show, :new, :edit, :update] do
    resources :bookings, only: [:new, :create, :destroy]
  end

  resources :bookings, only: [:update]


  resources :notifications, only: [] do
    collection do
      patch :mark_all_read
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :event
  enum status: { pending: "pending", accepted: "accepted", declined: "declined" }
end

app/models/event.rb
class Event < ApplicationRecord
  # --- Associations ---
  belongs_to :venue
  has_many :bookings
  has_many :users, through: :bookings # musicians who booked
  has_one_attached :photo

  # --- Validations ---
  validates :title, presence: true, length: { minimum: 3, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10 }
  validates :date, presence: true
  validates :time, presence: true
  validates :max_slots, presence: true, numericality: { only_integer: true, greater_than: 0, message: "must be a positive whole number" }
  validates :venue_id, presence: true

  # --- Scopes ---
  scope :upcoming, -> { where('date >= ?', Date.current).order(:date, :time) }
  scope :past, -> { where('date < ?', Date.current).order(date: :desc, time: :desc) }


end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :notifiable, polymorphic: true

  scope :unread, -> { where(read_at: nil) }

  # after_create_commit do
  #   # prepend the new notification into the list
  #   broadcast_prepend_to(
  #     user,
  #     target: "notifications_list",
  #     partial: "shared/notification_item",
  #     locals: { notification: self }
  #   )

  #   # update the badge count
  #   broadcast_replace_to(
  #     user,
  #     target: "notifications_count",
  #     partial: "shared/notification_count",
  #     locals: { count: user.notifications.unread.count }
  #   )
  # end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
# Include additional modules as needed
  has_many :venues
  has_many :bookings
  has_many :events, through: :bookings
  has_many :booked_events, through: :venues, source: :events
  has_many :booked_bookings, through: :booked_events, source: :bookings
  has_many :notifications, dependent: :destroy
  enum role: { musician: 0, organiser: 1 }
end

app/models/venue.rb
class Venue < ApplicationRecord
  belongs_to :user
  has_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :resource_name, :resource, :devise_mapping
  # before_action :authenticate_user!
  before_action :load_notifications

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    Devise.mappings[:user]
  end

  private

  def load_notifications
    return unless current_user
    @notifications = current_user.notifications.unread.order(created_at: :desc)
  end
end

app/controllers/bookings_controller.rb
# app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  # This line ENSURES a user is logged in before the 'create' action can run.
  before_action :authenticate_user!, only: [:new, :create, :update]
  # Ensure owners can accept or decline
  before_action :set_booking, only: [:update]
  before_action :authorize_owner!, only: [:update]

  def new
    @event = Event.find(params[:event_id])
    @booking = Booking.new
  end

  def create
    @event = Event.find(params[:event_id])
    @booking = @event.bookings.new(booking_params)
    @booking.user = current_user
    @booking.status = 'pending'
    if @booking.save
      redirect_to @event, notice: 'Booking was successfully created.'

      Notification.create!(
        user: @booking.event.venue.user,   # the venue owner
        action: "booking_requested",
        notifiable: @booking
      )
    else
      flash.now[:alert] = @booking.errors.full_messages.to_sentence
      render :new
    end
  end

  def update
  @booking = Booking.find(params[:id])

  # Set status (choose one approach)
  new_status = params[:booking]&.dig(:status) ||
               (params[:commit] == "Accept" ? "accepted" : "declined")

  if @booking.update(status: new_status)
    # Notify the musician
    Notification.create!(
      user:       @booking.user,
      action:     "booking_#{@booking.status}",
      notifiable: @booking
    )

    redirect_to dashboard_path, notice: "Booking #{@booking.status.humanize.downcase}."
  else
    flash.now[:alert] = @booking.errors.full_messages.to_sentence
    render :dashboard
  end
end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def authorize_owner!
    # Ensure current_user owns the event's venue
    unless @booking.event.venue.user == current_user
      redirect_to root_path, alert: "Not authorized."
    end
  end

  def booking_params
    params.require(:booking).permit(:event_id, :status).merge(user: current_user)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def show
    @event = Event.find(params[:id])
    @available_slots = @event.max_slots - @event.bookings.where.not(status: 'declined').count
    # Define if the user has already booked this event
    @has_booked = @event.bookings.exists?(user: current_user) if user_signed_in?
    # return booked status
    @booking_status = @event.bookings.find_by(user: current_user).status if user_signed_in? && @has_booked
    # Define if the event is in the past
    # @is_past = @event.date < Date.current || (@event.date == Date.current && @event.time < Time.current)
  end


  def index
    @events = Event.all
    @last_three = Event.last(3)
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to @event, notice: 'Event was successfully created.'
    else
      render :new
    end

  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to @event, notice: 'Event was successfully updated.'
    else
      render :edit
    end
  end

  private
  def event_params
    params.require(:event).permit(:title, :description, :date, :time, :max_slots, :photo).merge(user: current_user)
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def mark_all_read
    current_user.notifications.unread.update_all(read_at: Time.current)
    head :no_content
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def dashboard

    @bookings_as_musician = current_user.bookings
    @bookings_as_organiser = current_user.booked_bookings

  end

  def index
    @resource = User.new
    @resource_name = :user
    @devise_mapping = Devise.mappings[:user]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/_carousel.html.erb
<div id="carouselLastEvents" class="carousel slide mb-4" data-bs-ride="carousel" style="margin: 0 auto;">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselLastEvents" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselLastEvents" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselLastEvents" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <%# slide link to event path %>
    <%= link_to event_path(@last_three[0]) do %>
    <div class="carousel-item active">
      <%= cl_image_tag @last_three[0].photo.key, crop: :fill, width: 900, height: 400, class: "d-block w-100 carousel-img", alt: @last_three[0].title %>
      <div class="carousel-caption d-none d-md-block">
        <h5><%=  @last_three[0].title%></h5>
        <p><%=  @last_three[0].description%></p>
      </div>
    </div>
    <% end %>
    <%= link_to event_path(@last_three[0]) do %>
    <div class="carousel-item">
      <%= cl_image_tag @last_three[1].photo.key, crop: :fill, width: 900, height: 400, class: "d-block w-100 carousel-img", alt: @last_three[1].title %>
      <div class="carousel-caption d-none d-md-block">
        <h5><%=  @last_three[1].title%></h5>
        <p><%=  @last_three[1].description%></p>
      </div>
    </div>
    <% end %>
    <%= link_to event_path(@last_three[0]) do %>
    <div class="carousel-item">
      <%= cl_image_tag @last_three[2].photo.key, crop: :fill, width: 900, height: 400, class: "d-block w-100 carousel-img", alt: @last_three[2].title %>
      <div class="carousel-caption d-none d-md-block">
        <h5><%=  @last_three[2].title%></h5>
        <p><%=  @last_three[2].description%></p>
      </div>
    </div>
  </div>
    <% end %>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselLastEvents" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselLastEvents" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/events/_form.html.erb
<%# Form  with simpleform should have :title, :description, :date, :time, :max_slots, :photo (cloudinary) %>
<%= simple_form_for @event, html: { class: 'form-horizontal' } do |f| %>
  <%= f.error_notification %>

  <div class="form-group">
    <%= f.input :title, label: 'Event Title', input_html: { class: 'form-control' } %>
  </div>

  <div class="form-group">
    <%= f.input :description, label: 'Event Description', input_html: { class: 'form-control' } %>
  </div>
  <div class="form-group row">
    <div class="col-md-6">
    <%= f.input :date, label: 'Event Date', as: :string, input_html: { data: { controller: "datepicker" } } %>
    </div>
    <div class="col-md-6">
    <%= f.input :time, label: 'Event Time', as: :time, discard_minute: true, input_html: { class: 'form-control' } %>
    </div>
  </div>
  <div class="form-group">
  </div>
  <div class="form-group">
    <%= f.input :max_slots, label: 'Maximum Slots', input_html: { class: 'form-control' } %>
  </div>
  <div class="form-group">
    <%= f.input :photo, label: 'Event Photo', as: :file, input_html: { class: 'form-control' } %>
  </div>
  <div class="form-group">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>

  <% if @event.photo.attached? %>
  <div class="row">
    <div class="col-md-6 mx-auto">
      <h2>Current Photo</h2>
      <%= cl_image_tag @event.photo.key, height: 300, width: 400, crop: :fill %>
    </div>
  </div>
<% end %>
<% end %>

app/views/events/edit.html.erb
<div class="container">
  <h1> Edit Event</h1>

  <%= link_to 'Back', events_path, class: 'btn btn-secondary' %>

  <%= render 'form', event: @event %>
</div>

app/views/events/index.html.erb
<%= render 'carousel' %>
<div class="container" data-controller="events-filter-list">
  <div class="d-flex justify-content-between align-items-center mb-4">
    <div>
      <h1>Events</h1>
      <p>Showing <%= @events.count %> events</p>
    </div>
    <div>
      <div class="btn-group" role="group" aria-label="Event Filters">
        <button type="button" class="btn btn-outline-primary" data-action="click->events-filter-list#all" data-events-filter-list-target="allList">All</button>
        <button type="button" class="btn btn-outline-secondary" data-action="click->events-filter-list#this_week" data-events-filter-list-target="thisWeek">This Week</button>
        <button type="button" class="btn btn-outline-secondary" data-action="click->events-filter-list#next_week" data-events-filter-list-target="nextWeek">Next Week</button>
      </div>
    </div>
  </div>

  <div class="row"  data-events-filter-list-target="list">
    <% @events.each do |event| %>
      <div class="col-md-4 mb-4 event-card" data-event-date="<%= event.date %>">
        <%= link_to event_path(event) do %>
          <div class="card h-100 shadow-sm">
            <div class="img-index-card">
             <%= cl_image_tag event.photo.key, crop: :fill, class: "card-img-top", alt: event.title %>
            </div>
            <div class="card-body">
              <h5 class="card-title"><%= event.title %></h5>
              <p class="card-text"><%= event.description %></p>
              <p class="card-text">
                <strong><%= lucide_icon('calendar-heart') %></strong>
                <%= event.date.strftime("%B %d, %Y") %>
                &nbsp;&nbsp;
                <strong><%= lucide_icon("clock-#{event.time.strftime('%-I')}") %></strong>
                <%= event.time.strftime("%-I %p") %>
              </p>
              <p class="card-text"><strong><%= lucide_icon('list-music') %></strong> <%= event.max_slots %> slots</p>
              <p class="card-text"><strong><%= lucide_icon('map-pinned') %></strong> <%= event.venue.address %>, <%= event.venue.city %>, <%= event.venue.country %></p>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<div class="container">
  <h1> New Event</h1>

  <%= link_to 'Back', events_path, class: 'btn btn-secondary' %>
  <%= render 'form', event: @event %>
</div>

app/views/events/show.html.erb
  <main class="container py-4">
    <% if flash[:notice].present? %>
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= flash[:notice] %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
    <% if flash[:alert].present? %>
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <%= flash[:alert] %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>

    <section class="card shadow-lg border-0 mb-5 show-page-card">
      <div class="row g-0 align-items-stretch">
        <div class="col-md-7 p-0">
          <% if @event.photo.attached? %>
            <%= image_tag @event.photo, class: "img-fluid event-detail-img", alt: "Event Image: #{@event.title}" %>
          <% else %>
            <%= image_tag "test_pic.jpg", class: "img-fluid event-detail-img", alt: "No image available" %>
          <% end %>
        </div>
        <div class="col-md-5">

          <div class="card-body p-4 p-md-5">
            <h1 class="card-title fw-bold event-title-underline mb-4">
              <%= @event.title %>
            </h1>

            <div class="d-flex align-items-center mb-2">
              <span class="me-3"><%= lucide_icon('calendar-heart') %></span>
              <p class="card-text mb-0">
                <%= @event.date.strftime("%B %d, %Y") %>
              </p>
            </div>
            <div class="d-flex align-items-center mb-2">
              <span class="me-3"><%= lucide_icon("clock-#{@event.time.strftime('%-I')}") %></span>
              <p class="card-text mb-0">
                <%= @event.time.strftime("%I:%M %p") %>
              </p>
            </div>

            <% if @event.venue.present? %>
              <div class="d-flex align-items-center mb-2">
                <span class="me-3"><%= lucide_icon('store') %></span>
                <p class="card-text mb-0">
                  <%= @event.venue.name %>
                </p>
              </div>
              <div class="d-flex align-items-center mb-4">
                <span class="me-3"><%= lucide_icon('map-pinned') %></span>
                <p class="card-text mb-0">
                  <%= @event.venue.address %>
                </p>
              </div>
            <% end %>

            <div class="d-flex align-items-center mb-4">
              <span class="me-3"><%= lucide_icon('list-music') %></span>
              <p class="card-text mb-0">
              <span><strong><%= @available_slots %> slots</strong> available.</span>
              </p>
            </div>

            <hr class="my-4">
            <h5 class="fw-bold mb-3">About this Event:</h5>
            <p class="card-text mb-4 text-muted event-description">
              <%= @event.description %>
            </p>

            <%# button to book this event, only available if loggedin, if yes, check if this has been booked and return status %>
            <% if user_signed_in? %>
              <% if @has_booked %>
                <div class="mb-4">
                   <% if @booking_status == 'pending' %>
                  <button class="btn btn-secondary w-100" disable><%= @booking_status.capitalize %></button>
                  <div class="text-center w-100"> 🤔 Wait for the update</div>
                  <% elsif @booking_status == 'accepted' %>
                    <button class="btn btn-success w-100" disable><%= @booking_status.capitalize %></button>
                    <div class="text-center w-100"> 😁 Congratulations!</div>
                  <% elsif @booking_status == 'declined' %>
                    <button class="btn btn-danger w-100 text-white" disable><%= @booking_status.capitalize %></button>
                    <div class="text-center w-100"> 😔 Sorry...</div>
                  <% end %>
                </div>
              <% else %>
               <%= simple_form_for [@event, Booking.new], html: { class: 'form-horizontal' } do |f| %>
                  <div class="mb-4">
                    <%= f.hidden_field :event_id, value: @event.id %>
                    <%= f.button :submit, "Book Now", class: "btn btn-outline-primary w-100" %>
                  </div>
                <% end %>
              <% end %>
            <% end %>


            <div class="mt-4 text-center text-muted small">
              Share the fun:
              <a href="#" class="text-decoration-none mx-2"><i class="fab fa-facebook-f"></i></a>
              <a href="#" class="text-decoration-none mx-2"><i class="fab fa-twitter"></i></a>
              <a href="#" class="text-decoration-none mx-2"><i class="fab fa-instagram"></i></a>
            </div>
          </div>
        </div>
      </div>
    </section>
  </main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NextGig</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="icon" type="image/png" href="<%= asset_path 'icon.png' %>">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
   <header class="navbar-app-dark-bg p-3 mb-3 border-bottom">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start text-white">
      <a href="<%= root_path %>" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
        <%= image_tag "logo.svg", width: 40, height: 32, alt: "NextGig Logo", class: "me-2" %>
      </a>
      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><a href="<%= root_path %>" class="nav-link px-2 text-white">Home</a></li>
      </ul>
      <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3 d-none" role="search">
        <input type="search" class="form-control form-control-dark text-bg-light" placeholder="Search..." aria-label="Search">
      </form>
      <div class="text-end d-flex align-items-center">
        <%= render "shared/login_modal" %>
      </div>
    </div>
  </div> </header>
       <%= yield %>

      <div class="container">
        <footer class="py-3 my-4">
          <ul class="nav justify-content-center border-bottom pb-3 mb-3">

          </ul> <p class="text-center text-body-secondary">© 2025 Company, Inc</p> </footer> </div>
  </body>
</html>

app/views/notifications/mark_all_read.html.erb
<h1>Notifications#mark_all_read</h1>
<p>Find me in app/views/notifications/mark_all_read.html.erb</p>

app/views/pages/dashboard.html.erb
<% if current_user.role == 'musician' %>
  <div class="container mt-4">
    <div class="p-3 mb-2 bg-light rounded-3">
      <h2>My Bookings</h2>
    </div>
  <table class="table table-bordered table-hover">
  <thead class="table-light">
    <tr class="sticky-top">
      <th>Date</th>
      <th>Venue</th>
      <th>Event</th>
      <th>Booking Status</th>
    </tr>
  </thead>
  <tbody>
 <% @bookings_as_musician.each do |booking| %>
    <tr>
      <td><%= booking.event.date %></td>
      <td><%= booking.event.venue.address %></td>
      <td><%= booking.event.title %></td>
      <td><%= booking.status %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<% elsif current_user.role == 'organiser' %>
  <div class="container mt-4">
    <div class="p-5 mb-4 bg-light rounded-3">
      <h2>My Events</h2>

  <table class="table table-bordered table-hover">
  <thead class="table-light">
    <tr class="sticky-top">
      <th>#</th>
      <th>Musician/ Band name</th>
      <th>Date</th>
      <th>Event</th>
      <th>Action</th>
      <th>Booking Status</th>
    </tr>
  </thead>
  <tbody>
   <% @bookings_as_organiser.each do |booking|%>

    <tr>
      <td><%= booking.id %></td>
      <td><%= booking.user.name %></td>
      <td><%= booking.event.date %></td>
      <td><%= booking.event.title %></td>
      <td><div class="input-group justify-content-center">
        <%= simple_form_for [booking] do |f| %>
          <%= f.submit "Accept", class: "btn btn-outline-success rounded-pill btn-lg m-2" %>
          <%= f.submit "Decline", class: "btn btn-outline-danger rounded-pill btn-lg m-2" %>
        <% end %>
      </div></td>
      <td><%= booking.status %></td>
    </tr>
    <% end %>
  </tbody>
  </table>
<% end%>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_login_modal.html.erb
<% if user_signed_in? %>
<%# the button logout should be hidden, only open as options when clicks on user name %>
<div class="dropdown me-2">

  <span class="badge bg-secondary"><%= current_user.role.capitalize %></span>
  <button class="btn btn-outline-light dropdown-toggle" type="button" id="userDropdown" data-bs-toggle="dropdown" aria-expanded="false">
    <%= current_user.name %>
  </button>
  <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdown">
    <li><a class="dropdown-item" href="<%= edit_user_registration_path %>">Profile</a></li>
    <li><a class="dropdown-item" href="<%= dashboard_path %>">Dashboard</a></li>
    <li><hr class="dropdown-divider"></li>
    <li><%= button_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
  </ul>
</div>
<%= render "shared/notifications_dropdown" %>
<% else %>
  <button type="button" class="btn btn-outline-light" data-bs-toggle="modal" data-bs-target="#loginModal">
    Login
  </button>

  <div class="modal fade right" id="loginModal" tabindex="-1" aria-labelledby="loginModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content h-100 border-0 rounded-0">
        <div class="modal-header">
          <h5 class="modal-title" id="loginModalLabel">Log in</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
        </div>
        <% resource      = User.new             %>
        <% resource_name = :user                 %>
        <% devise_mapping = Devise.mappings[:user] %>
        <div class="modal-body">
          <%= render "devise/sessions/form",
                resource:       resource,
                resource_name:  resource_name,
                devise_mapping: devise_mapping %>
        </div>
      </div>
    </div>
  </div>
  <button type="button" class="btn btn-warning mx-2">Sign-up</button>
<% end %>

app/views/shared/_notification_count.html.erb
<%= count %>

app/views/shared/_notification_item.html.erb
<li class="dropdown-item" id="<%= dom_id(notification) %>">
  <% case notification.action %>
  <% when "booking_requested" %>
    🎤 <%= link_to "#{notification.notifiable.user.name} requested “#{notification.notifiable.event.title}”", dashboard_path %>
  <% when "booking_accepted" %>
    ✅ Your spot at <%= link_to notification.notifiable.event.title, dashboard_path %> was accepted
  <% when "booking_declined" %>
    ❌ Your spot at <%= link_to notification.notifiable.event.title, dashboard_path %> was declined
  <% end %>
  <br>
  <small class="text-muted"><%= time_ago_in_words(notification.created_at) %> ago</small>
</li>

app/views/shared/_notifications_dropdown.html.erb
<div id="notifications_menu" data-controller="dropdown">

  <button class="btn position-relative text-white" data-bs-toggle="dropdown">
    <%= lucide_icon("bell") %>
    <span id="notifications_count" class="badge bg-danger position-absolute top-0 start-100 translate-middle">
      <%= @notifications.count %>
    </span>
  </button>

  <ul id="notifications_list" class="dropdown-menu dropdown-menu-end">
    <%= render partial: "shared/notification_item", collection: @notifications, as: :notification %>
    <li><hr class="dropdown-divider"></li>
    <li>
      <%= button_to "Mark all as read",
                    mark_all_read_notifications_path,
                    method: :patch,
                    remote: true,
                    class: "dropdown-item text-center" %>
    </li>
  </ul>
</div>